;Also known as PROJECT KAKUMEI in Discord
Name=最強革命 -saikyo kakumei-
Version=Kαkumei
Creator=TFD500 (vs. DashyDesu)
Resolution=1920,1080
FontName=Fonts/ShipporiMinchoB1-SemiBold.ttf
BoxFontName=Fonts/MPLUSRounded1c-Regular.ttf

FontNameEN=Fonts/ShipporiMinchoB1-SemiBold.ttf
FontNameJA=Fonts/ShipporiMinchoB1-SemiBold.ttf
FontNameFR=Fonts/ShipporiMinchoB1-SemiBold.ttf
FontNameES=Fonts/ShipporiMinchoB1-SemiBold.ttf
FontNameNL=Fonts/ShipporiMinchoB1-SemiBold.ttf
FontNameDE=Fonts/ShipporiMinchoB1-SemiBold.ttf
FontNameRU=Fonts/ShipporiMinchoB1-SemiBold.ttf
FontNameKO=Fonts/ResourceHanRoundedKR-Medium.ttf
FontNameZH=Fonts/ResourceHanRoundedCN-Medium.ttf
BoxFontNameEN=Fonts/ZenAntiqueSoft-Regular.ttf
BoxFontNameJA=Fonts/ZenAntiqueSoft-Regular.ttf
BoxFontNameFR=Fonts/ZenAntiqueSoft-Regular.ttf
BoxFontNameES=Fonts/ZenAntiqueSoft-Regular.ttf
BoxFontNameNL=Fonts/ZenAntiqueSoft-Regular.ttf
BoxFontNameDE=Fonts/ZenAntiqueSoft-Regular.ttf
BoxFontNameRU=Fonts/ZenAntiqueSoft-Regular.ttf
BoxFontNameKO=Fonts/ResourceHanRoundedKR-Regular.ttf
BoxFontNameZH=Fonts/ResourceHanRoundedCN-Regular.ttf

#include OtherConfig.ini
#include TitleConfig.ini
#include ConfigConfig.ini
#include SongSelectConfig.ini
#include HeyaConfig.ini
#include SongLoadingConfig.ini
#include GameConfig.ini
#include ModIconsConfig.ini
#include NameplateConfig.ini
#include AIResultConfig.ini
#include ResultConfig.ini
#include DaniSelectConfig.ini
#include DanResultConfig.ini
#include TowerResultConfig.ini
#include TowerSelectConfig.ini
#include OnlineLoungeConfig.ini
#include OpenEncyclopediaConfig.ini
#include ModalConfig.ini
#include Game4PConfig.ini
#include Result4PConfig.ini
#include Modal4PConfig.ini